config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }, as: 'client'
    root 'users/home#index', as: 'client_root'
    scope module: :users do
      resource :profiles
      resource :invite
      resources :lottery, only: [:index, :show, :create]
      resources :addresses, except: :show
    end
  end

  constraints(AdminDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'admin/sessions'
    }, as: 'admin'
    root 'admin/home#index', as: 'admin_root'
    scope module: :admin do
      resources :users, only: :index
      resources :categories
      resources :items do
        patch :start
        patch :pause
        patch :end
        patch :cancel
      end
      resources :bets, only: [:index] do
        patch :won
        patch :lost
        patch :cancel
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/address/barangay.rb
class Address::Barangay < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :city
  has_many :addresses, class_name: 'Address', foreign_key: 'address_barangay_id'
end

app/models/address/city.rb
class Address::City < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :province
  has_many :barangays
  has_many :addresses, class_name: 'Address', foreign_key: 'address_city_id'
end

app/models/address/province.rb
class Address::Province < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region
  has_many :cities
end

app/models/address/region.rb
class Address::Region < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  has_many :provinces
  has_many :addresses, class_name: 'Address', foreign_key: 'address_region_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses
  has_many :items
  has_many :bets
  belongs_to :parent, class_name: 'User', optional: true, counter_cache: :children_members
  has_many :children, class_name: 'User', foreign_key: :parent_id
  mount_uploader :image, ImageUploader

  enum role: { client: 0, admin: 1 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users = User.all
  end

end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
  before_action :set_address, only: [:edit, :update, :destroy]

  def index
    @addresses = current_client_user.addresses
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_client_user
    if @address.save
      flash[:notice] = 'Address created successfully'
      redirect_to addresses_path
    else
      flash.now[:alert] = 'Address create failed'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      flash[:notice] = 'Address updated successfully'
      redirect_to addresses_path
    else
      flash.now[:alert] = 'Address update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @address.destroy
    flash[:notice] = 'Address destroyed successfully'
    redirect_to addresses_path
  end

  private

  def set_address
    @address = current_client_user.addresses.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:genre, :name, :street_address, :phone_number, :remark, :is_default, :user, :address_region_id, :address_province_id, :address_city_id, :address_barangay_id)
  end
end

app/controllers/users/home_controller.rb
class Users::HomeController < ApplicationController
  def index;end

end

app/controllers/users/invites_controller.rb
class Users::InvitesController < ApplicationController

  def show
    if current_client_user
      @promoter_link = "client.com:3000/users/sign_up?promoter=#{current_client_user.email}"
    else
      @promoter_link = "client.com:3000/users/sign_up"
    end
    qrcode = RQRCode::QRCode.new(@promoter_link)

    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 11,
      standalone: true,
      use_path: true
    )
  end
end

app/controllers/users/lottery_controller.rb
class Users::LotteryController < ApplicationController
    before_action :authenticate_client_user!, except: :index
    def index
      @items = Item.active.starting.where("offline_at >= (?) AND online_at <= (?)", Date.current, Date.current)
      @items = @items.includes(:categories).where(categories: { id: params[:category] }) if params[:category].present?
    end

    def show
      @item = Item.find(params[:id])
      @bet = Bet.new
      @bets = current_client_user.bets.where(item: @item, batch_count: @item.batch_count)
      @progress = (Bet.where(item: @item, batch_count: @item.batch_count).count/@item.minimum_bets.to_f) * 100
    end

    def create
      bet_counts = params[:bet][:bet_count]
      bet_counts.to_i.times do
        bet = Bet.create(batch_count: params[:item_batch_count],
                         user_id: current_client_user.id, item_id: params[:item_id])
      end
      flash[:notice] = 'Bet Successfully'
      redirect_to lottery_index_path
    end
  end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  def show; end

  def edit
    @user = current_client_user
  end

  def update
    @user = current_client_user
    if @user.update(user_params)
      redirect_to profiles_path, notice: 'User was successfully updated.'
    end
  end

  def user_params
    params.permit(:phone_number, :username, :password)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def new
    cookies[:promoter] ||= params[:promoter]
    super
  end

  # POST /resource
  def create
    super
    parent = User.find_by(email: cookies[:promoter])
    self.resource.update(parent: parent)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  def create
    user = User.find_by(email: params[:client_user][:email])
    if user&.client?
      super
    else
      flash[:alert] = "Wrong email or password"
      redirect_to new_client_user_session_path
    end
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_out_path_for(resource_or_scope)
    new_client_user_session_path
  end
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/addresses/_form.html.erb
<%= form_with model: address, data: { controller: :location } do |form| %>
  <% if address.errors.any? %>
    <ul>
      <% address.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :genre %>
    <% Address.genres.each do |genre, value| %>
      <%= form.radio_button :genre, genre, checked: address.genre == genre %>
      <%= label :genre, genre.humanize %>
    <% end %>
  </div>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>
  <div>
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>
  <div>
    <%= form.label :remark %>
    <%= form.text_area :remark %>
  </div>
  <div>
    <%= form.label :is_default %>
    <%= form.check_box :is_default, {}, true, false %>
  </div>
  <div>
    <%= form.label :address_region_id %>
    <%= form.collection_select :address_region_id,
                               Address::Region.all, :id, :name,
                               { prompt: 'Please select region' },
                               data: { location_target: 'selectedRegionId', action: 'change->location#fetchProvinces' } %>
  </div>

  <div>
    <%= form.label :province_id %>
    <%= form.collection_select :address_province_id,
                               [], nil, nil,
                               { prompt: 'Please select province' },
                               data: { location_target: 'selectedProvinceId', action: 'change->location#fetchCities' } %>
  </div>
  <div>
    <%= form.label :city_id %>
    <%= form.collection_select :address_city_id,
                               [], nil, nil,
                               { prompt: 'Please select city' },
                               data: { location_target: 'selectedCityId', action: 'change->location#fetchBarangays' } %>
  </div>
  <div>
    <%= form.label :barangay_id %>
    <%= form.collection_select :address_barangay_id,
                               [], nil, nil,
                               { prompt: 'Please select barangay' },
                               data: { location_target: 'selectedBarangayId' } %>
  </div>
  <%= form.submit %>
<% end %>

app/views/users/addresses/edit.html.erb
<h1>Edit Post id: <%= @address.id %></h1>
<%= render partial: 'form', locals: { address: @address} %>

app/views/users/addresses/index.html.erb
<table class="table table-sm">
  <thead>
  <td>Genre</td>
  <td>Name</td>
  <td>Street Address</td>
  <td>Phone Number</td>
  <td>Remark</td>
  <td>Default</td>
  <td>Address</td>
  </thead>
  <% @addresses.each do |address| %>
    <tr>
      <td><%= address.genre %></td>
      <td><%= address.name %></td>
      <td><%= address.street_address %></td>
      <td><%= address.phone_number %></td>
      <td><%= address.remark %></td>
      <td><%= address.is_default %></td>
      <td><%= "#{address.region&.name} #{address.province&.name} #{address.city&.name} #{address.barangay&.name}" %></td>
      <td>
        <%= link_to 'Edit', edit_address_path(address) %>
        <%= button_to 'Delete', address_path(address), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'new', new_address_path%>

app/views/users/addresses/new.html.erb
<h1>New Post</h1>
<%= render partial: 'form', locals: { address: @address } %>