config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }, as: 'client'
    root 'users/home#index', as: 'client_root'
    scope module: :users do
      resource :profiles
      resource :invite
      resources :lottery, only: [:index, :show, :create]
      resources :addresses, except: :show
    end
  end

  constraints(AdminDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'admin/sessions'
    }, as: 'admin'
    root 'admin/home#index', as: 'admin_root'
    scope module: :admin do
      resources :users, only: :index
      resources :categories
      resources :items do
        patch :start
        patch :pause
        patch :end
        patch :cancel
      end
      resources :bets, only: [:index] do
        patch :won
        patch :lost
        patch :cancel
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses
  has_many :items
  has_many :bets
  belongs_to :parent, class_name: 'User', optional: true, counter_cache: :children_members
  has_many :children, class_name: 'User', foreign_key: :parent_id
  mount_uploader :image, ImageUploader

  enum role: { client: 0, admin: 1 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users = User.all
  end

end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
  before_action :set_address, only: [:edit, :update, :destroy]

  def index
    @addresses = current_client_user.addresses
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_client_user
    if @address.save
      flash[:notice] = 'Address created successfully'
      redirect_to addresses_path
    else
      flash.now[:alert] = 'Address create failed'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      flash[:notice] = 'Address updated successfully'
      redirect_to addresses_path
    else
      flash.now[:alert] = 'Address update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @address.destroy
    flash[:notice] = 'Address destroyed successfully'
    redirect_to addresses_path
  end

  private

  def set_address
    @address = current_client_user.addresses.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:genre, :name, :street_address, :phone_number, :remark, :is_default, :user, :address_region_id, :address_province_id, :address_city_id, :address_barangay_id)
  end
end

app/controllers/users/home_controller.rb
class Users::HomeController < ApplicationController
  def index;end

end

app/controllers/users/invites_controller.rb
class Users::InvitesController < ApplicationController

  def show
    if current_client_user
      @promoter_link = "client.com:3000/users/sign_up?promoter=#{current_client_user.email}"
    else
      @promoter_link = "client.com:3000/users/sign_up"
    end
    qrcode = RQRCode::QRCode.new(@promoter_link)

    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 11,
      standalone: true,
      use_path: true
    )
  end
end

app/controllers/users/lottery_controller.rb
class Users::LotteryController < ApplicationController
    before_action :authenticate_client_user!, except: :index
    def index
      @items = Item.active.starting.where("offline_at >= (?) AND online_at <= (?)", Date.current, Date.current)
      @items = @items.includes(:categories).where(categories: { id: params[:category] }) if params[:category].present?
    end

    def show
      @item = Item.find(params[:id])
      @bet = Bet.new
      @bets = current_client_user.bets.where(item: @item, batch_count: @item.batch_count)
      @progress = (Bet.where(item: @item, batch_count: @item.batch_count).count/@item.minimum_bets.to_f) * 100
    end

    def create
      bet_counts = params[:bet][:bet_count]
      bet_counts.to_i.times do
        bet = Bet.create(batch_count: params[:item_batch_count],
                         user_id: current_client_user.id, item_id: params[:item_id])
      end
      flash[:notice] = 'Bet Successfully'
      redirect_to lottery_index_path
    end
  end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  def show; end

  def edit
    @user = current_client_user
  end

  def update
    @user = current_client_user
    if @user.update(user_params)
      redirect_to profiles_path, notice: 'User was successfully updated.'
    end
  end

  def user_params
    params.permit(:phone_number, :username, :password)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def new
    cookies[:promoter] ||= params[:promoter]
    super
  end

  # POST /resource
  def create
    super
    parent = User.find_by(email: cookies[:promoter])
    self.resource.update(parent: parent)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  def create
    user = User.find_by(email: params[:client_user][:email])
    if user&.client?
      super
    else
      flash[:alert] = "Wrong email or password"
      redirect_to new_client_user_session_path
    end
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_out_path_for(resource_or_scope)
    new_client_user_session_path
  end
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/lottery/index.html.erb
<div class="container">
  <div id="myCarousel" class="carousel slide mt-2" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
          <rect width="150%" height="100%" fill="var(--bs-secondary-color)"/>
        </svg>
        <div class="container">
          <div class="carousel-caption text-start">
            <img src="https://thehappytrip.com/wp-content/uploads/2019/05/SanAntonioZambalesjf9052_08.jpg" class="img-fluid" width="">
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
          <rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
        </svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
          <rect width="100%" height="100%" fill="var(--bs-secondary-color)"/>
        </svg>
        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="alert alert-dark" role="alert">
    Announcement:
  </div>
  <div class="d-grid gap-2">
    <button type="button" class="btn btn-outline-success">Button</button>
  </div>
</div>

<div class="container marketing " style="height: 1000px">
  <%= link_to 'All', lottery_index_path, class: 'btn btn-secondary' %>
  <% Category.all.each do |category| %>
    <%= link_to category.name, lottery_index_path(category: category), class: 'btn btn-secondary' %>
  <% end %>
  <div class="row">
    <% @items.each do |item| %>
      <%= link_to lottery_path(item) do %>
        <div class="col-3 mb-5">
          <div class="card" style="width: 18rem;">
            <%= image_tag item.image.url, width: "100px", height: "100px", class: "card-img-top" if item.image.present? %>
            <div class="card-body">
              <%= item.name %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/lottery/show.html.erb
<div class="container border text-center align-self-center w-auto ms-5">
  <div class="text-center">
    <div class="card" style="width: 18rem;">
      <%= image_tag @item.image.url, width: "100px", height: "100px", class: "card-img-top" if @item.image.present? %>
      <div class="card-body">
        <%= @item.name %>
      </div>
    </div>
  </div>
  <table>
    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width: <%= @progress %>%" aria-valuenow="<%= @progress %>" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <%= form_with model: @bet, url: lottery_index_path, data: { turbo: false } do |form| %>
      <%= form.number_field :bet_count %>
      <%= hidden_field_tag :item_batch_count, value = @item.batch_count %>
      <%= hidden_field_tag :item_id, value = @item.id %>
      <%= form.submit %> <br/>
    <% end %>

    <% @item.bets.each do |bet| %>
      <tr>
        <td> <%= bet.serial_number %> </td>
      </tr>
    <% end %>
  </table>
</div>