config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }, as: 'client'
    root 'users/home#index', as: 'client_root'
    scope module: :users do
      resource :profiles
      resource :invite
      resources :lottery, only: [:index, :show, :create]
      resources :addresses, except: :show
    end
  end

  constraints(AdminDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'admin/sessions'
    }, as: 'admin'
    root 'admin/home#index', as: 'admin_root'
    scope module: :admin do
      resources :users, only: :index
      resources :categories
      resources :items do
        patch :start
        patch :pause
        patch :end
        patch :cancel
      end
      resources :bets, only: [:index] do
        patch :won
        patch :lost
        patch :cancel
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :items_category_ships
  has_many :items, through: :items_category_ships
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created successfully'
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category updated successfully'
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    begin
      @category.destroy
      flash[:notice] = 'Category deleted successfully'
    rescue ActiveRecord::DeleteRestrictionError => e
      flash[:alert] = 'Cannot delete category because it has dependent items.'
    end
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: category, url: url, method: method, data: { turbo: false }) do |form| %>
  <div>
    <%= form.label :name %>

    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render partial: 'form', locals: {model: @category, url: category_path, method: :patch  } %>

app/views/admin/categories/index.html.erb
<div class="mx-auto" style="width: 200px;">
  <h1>Category</h1>
  <table class="table table-dark">
    <thead>
    <td>Name</td>
    <td>Action</td>
    </thead>
  </table>
  <ul>
    <% @categories.each do |category| %>
      <li>
        <%= category.name %>
        <td>
          <%= link_to :edit, edit_category_path(category) %><br>
          <%= button_to :delete, category_path(category), method: :delete %><br>
        </td>
      </li>
    <% end %>
  </ul>
</div>

<button><%= link_to 'new', new_category_path, class: "btn btn-light" %></button>

app/views/admin/categories/new.html.erb
<div class="mx-auto mt-5" style="width: 200px;">
<%= render partial: 'form', locals: { category: @category, url: categories_path, method: :post } %>
</div>