config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }, as: 'client'
    root 'users/home#index', as: 'client_root'
    scope module: :users do
      resource :profiles
      resource :invite
      resources :lottery, only: [:index, :show, :create]
      resources :addresses, except: :show
    end
  end

  constraints(AdminDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'admin/sessions'
    }, as: 'admin'
    root 'admin/home#index', as: 'admin_root'
    scope module: :admin do
      resources :users, only: :index
      resources :categories
      resources :items do
        patch :start
        patch :pause
        patch :end
        patch :cancel
      end
      resources :bets, only: [:index] do
        patch :won
        patch :lost
        patch :cancel
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end
      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  enum genre: { home: 0, office: 1 }

  belongs_to :user
  belongs_to :region, class_name: 'Address::Region', foreign_key: 'address_region_id'
  belongs_to :province, class_name: 'Address::Province', foreign_key: 'address_province_id'
  belongs_to :city, class_name: 'Address::City', foreign_key: 'address_city_id'
  belongs_to :barangay, class_name: 'Address::Barangay', foreign_key: 'address_barangay_id'
end

app/models/address/barangay.rb
class Address::Barangay < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :city
  has_many :addresses, class_name: 'Address', foreign_key: 'address_barangay_id'
end

app/models/address/city.rb
class Address::City < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :province
  has_many :barangays
  has_many :addresses, class_name: 'Address', foreign_key: 'address_city_id'
end

app/models/address/province.rb
class Address::Province < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region
  has_many :cities
end

app/models/address/region.rb
class Address::Region < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  has_many :provinces
  has_many :addresses, class_name: 'Address', foreign_key: 'address_region_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bet.rb
class Bet < ApplicationRecord
  include AASM

  scope :filter_by_serial_number, -> (serial_number) { where serial_number: serial_number }
  scope :filter_by_item_name, -> (item_name) { includes(:item).where(item: {name: item_name}) }
  scope :filter_by_email, -> (email) { includes(:user).where(user: {email: email }) }
  scope :filter_by_state, -> (state) { where state: state }
  scope :filter_by_start_date, -> (start_date) { where("offline_at >= (?)", start_date)}
  scope :filter_by_end_date, -> (end_date) { where("offline_at < (?)", end_date) }

  belongs_to :item
  belongs_to :user

  after_create :assign_serial_number
  after_create :subtract_coin

  aasm column: :state do
    state :betting, initial: true
    state :won, :lost, :cancelled

    event :won do
      transitions from: :betting, to: :won
    end

    event :lost do
      transitions from: :betting, to: :lost
    end

    event :cancel do
      transitions from: :betting, to: :cancelled, after: :refund_coin
    end
  end

  private

  def subtract_coin
    user.update(coins: user.coins - 1)
  end

  def refund_coin
    user.update(coins: user.coins + 1)
  end

  def assign_serial_number
    number_count = format('%04d', item.bets.where(batch_count: item.batch_count).count)
    date_format = Time.current.strftime('%y%m%d')
    serial_number = "#{date_format}-#{item.id}-#{item.batch_count}-#{number_count}"
    update(serial_number: serial_number)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :items_category_ships
  has_many :items, through: :items_category_ships
end

app/models/item.rb
class Item < ApplicationRecord
  include AASM

  validates :image, :name, :quantity, :minimum_bets, :batch_count, :online_at, :offline_at, :start_at, presence: :true

  has_many :bets
  has_many :items_category_ships
  has_many :categories, through: :items_category_ships

  validates :name, presence: true
  validates :quantity, presence: true

  default_scope { where(deleted_at: nil) }

  mount_uploader :image, ImageUploader
  enum status: { active: 0, inactive: 1 }


  aasm column: :state do
    state :pending, initial: true
    state :starting, :paused, :ended, :cancelled

    event :start do
      transitions from: [:pending, :ended, :cancelled], to: :starting
    end

    event :pause do
      transitions from: :starting, to: :paused
    end

    event :end do
      transitions from: :starting, to: :ended
    end

    event :cancel do
      transitions from: [:starting, :paused], to: :cancelled
    end

  end

  def destroy
    update(deleted_at: Time.current)
  end
end

app/models/items_category_ship.rb
class ItemsCategoryShip < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses
  has_many :items
  has_many :bets
  belongs_to :parent, class_name: 'User', optional: true, counter_cache: :children_members
  has_many :children, class_name: 'User', foreign_key: :parent_id
  mount_uploader :image, ImageUploader

  enum role: { client: 0, admin: 1 }
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_client_header.html.erb
<main>
  <style>
      .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
      }

      @media (min-width: 768px) {
          .bd-placeholder-img-lg {
              font-size: 3.5rem;
          }
      }

      .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
      }

      .bi {
          vertical-align: -.125em;
          fill: currentColor;
      }

      .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
      }

      .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
          z-index: 1500;
      }

      .carousel-item {
          height: 35rem;
      }
  </style>
  <nav class="navbar bg-body-tertiary fixed-top d-flex flex-wrap justify-content-center py-1 mb-4 border-bottom">
    <div class="container-fluid">
      <%= link_to client_root_path, class: "navbar-brand d-flex align-items-center mb-4 mb-md-0 me-md-5 text-dark text-decoration-none" do %>
        <h4><%= client_user_signed_in? ? 'LOGO' : 'Brand Image' %></h4>
      <% end %>
      <ul class="ms-auto mt-3">
        <a class="nav-item text-decoration-none text-black me-2" href="#">Coins</a>
        <a class="nav-item text-decoration-none text-black me-2" href="#">Claim</a>
        <a class="nav-item text-decoration-none text-black me-2" href="#">Language</a>
        <%= link_to 'Sign in', new_client_user_session_path, class: "nav-item text-decoration-none text-black me-2" if !client_user_signed_in? %>
      </ul>
      <% if client_user_signed_in? %>
        <button class="navbar-toggler border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu Views</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Username: <%= current_client_user.username %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Email: <%= current_client_user.email %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Coins: <%= current_client_user.coins.present? ? current_client_user.coins : '0' %></a>
              </li>
              <button class="btn btn-dark w-100" type="button">Cash In Now</button>

              <div class="dropdown-center mt-2">
                <button class="btn btn-dark w-100 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Settings
                </button>
                <ul class="dropdown-menu ms-auto">
                  <li><a class="dropdown-item" href="#">Contact Us</a></li>
                  <li class="dropdown-item"><%= link_to 'My Profile', profiles_path, class: "nav-item text-decoration-none text-black me-2" %></li>
                  <li class="dropdown-item"><%= link_to 'Sign out', destroy_client_user_session_path, data: { 'turbo-method': :delete } %></li>
                </ul>
              </div>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </nav>

  <nav class="navbar bg-body-tertiary fixed-bottom">
    <div class="container-fluid">
      <ul class="ms-auto me-auto pt-2">
        <a class="nav-item text-decoration-none text-black me-2" href="#">Share</a>
        <%= link_to 'Invite', invite_path, class: "nav-item text-decoration-none text-black me-2" %>
        <%= link_to 'Lottery', lottery_index_path, class: "nav-item text-decoration-none text-black me-2" %>
        <a class="nav-item text-decoration-none text-black me-2" href="#">Shop</a>
        <%= link_to 'Me', profiles_path, class: "nav-item text-decoration-none text-black me-2" if current_client_user %>
      </ul>
    </div>
  </nav>
</main>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
  <meta name="theme-color" content="#7952b3">

</head>
<% if current_admin_user %>
  <nav class="navbar bg-body-secondary">
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Home</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>

      <div class="dropdown-center mt-2">
        <button class="btn btn-dark w-100 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Member Management
        </button>
        <ul class="dropdown-menu ms-auto">
          <li><a class="dropdown-item" href="#">User List</a></li>
          <li class="dropdown-item"><%= link_to 'Item List', items_path %></li>
          <li class="dropdown-item"><%= link_to 'Category List', categories_path %></li>
          <li class="dropdown-item"><%= link_to 'Bets', bets_path %></li>
        </ul>
      </div>

      <div class="dropdown-center mt-2">
        <button class="btn btn-dark w-100 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Example 2 Management
        </button>
        <ul class="dropdown-menu ms-auto">
          <li><a class="dropdown-item" href="#">Example 1</a></li>
          <li><a class="dropdown-item" href="#">Example 2</a></li>
        </ul>
      </div>
    </div>

    <div class="container-fluid">
      <button class="navbar-toggler border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">System Management</a>
      <ul class="ms-auto">
        <a class="nav-item text-decoration-none text-black me-md-2" href="#">Change Language</a>
        <div class="btn-group">
          <button type="button" class="btn btn-outline-secondary">Username</button>
          <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split me-md-5" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li class="dropdown-item"><%= link_to 'Sign out', destroy_client_user_session_path, data: { 'turbo-method': :delete } %></li>
          </ul>
        </div>
      </ul>
    </div>
  </nav>
<% end %>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= render 'layouts/admin_header' if current_admin_user %>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
  <meta name="theme-color" content="#7952b3">
</head>

<body>
<% if flash[:notice] %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if flash[:alert] %>
  <p class="alert"><%= alert %></p>
<% end %>
<%= render 'layouts/client_header' %>
<%= yield %>
</body>
</html>